### ISSUE TITLE
EMF Error

### ISSUE THREAD

**Issue by Joseahfer** [EquilinoxModdingFramework/EquilinoxModdingFramework#2]
Log seems fine:
```
[EMF] Found framework file at: C:\Program%20Files%20(x86)\Steam\steamapps\common\Equilinox\EquilinoxModdingFramework-1.0.7-1.2.5.jar
[EMF] Found game file at: C:\Program Files (x86)\Steam\steamapps\common\Equilinox\EquilinoxWindows.jar
[EMF] Backup of the game file already exists.
[EMF] Reading patches...
[EMF] Processing 0 patches...
[EMF] Extracting framework files...
[EMF] Game patched.
```

But in the error txt:
```
java.io.FileNotFoundException: C:\Program%20Files%20(x86)\Steam\steamapps\common\Equilinox\EquilinoxModdingFramework-1.0.7-1.2.5.jar (El sistema no puede encontrar la ruta especificada)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at kd.equilinox.launcher.patches.GamePatcher.readPatches(GamePatcher.java:56)
	at kd.equilinox.launcher.patches.GamePatcher.run(GamePatcher.java:41)
	at kd.equilinox.launcher.Main.patchGame(Main.java:45)
	at kd.equilinox.launcher.Main.main(Main.java:24)
[EMF] Error when patching game file.
java.io.IOException: Cannot run program "jar": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at kd.equilinox.launcher.patches.PatchApplier.injectEMFClasses(PatchApplier.java:59)
	at kd.equilinox.launcher.patches.PatchApplier.run(PatchApplier.java:43)
	at kd.equilinox.launcher.patches.FilePatcher.applyPatches(FilePatcher.java:51)
	at kd.equilinox.launcher.patches.FilePatcher.run(FilePatcher.java:46)
	at kd.equilinox.launcher.patches.GamePatcher.processPatches(GamePatcher.java:50)
	at kd.equilinox.launcher.patches.GamePatcher.run(GamePatcher.java:44)
	at kd.equilinox.launcher.Main.patchGame(Main.java:45)
	at kd.equilinox.launcher.Main.main(Main.java:24)
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 12 more
```

**Comment by Sejoslaw** [comment]
Make sure that you have "jar" added to your path.
To check it just open command line and type "jar" - should should see an error (that's what the error log says).
